### ISSUE TITLE
Changes to allow for Amazon slot types

### ISSUE THREAD

**Issue by mylesrankin** [pavelsavara/serverless-plugin-lex-bot#1]
Hi, 

Currently need to use your plugin for deploying a Lex bot automatically in our CI system. I've forked the repo and made a couple changes, so that it allows the use of Amazon slot types like 'AMAZON.Person', 'AMAZON.Organisation', etc... I also changed the timeout lengths, as I was hitting a LimitExceptionError, this seemed to reduce the number of times this error occurred. Would it be okay to submit a pull request for these changes? As there is no Contributing.md in your repository, I am unclear of the guidelines to this. Furthermore, would it be possible to publish the repository to npm and/or serverless plugin directory?

Checkout the Fork: https://github.com/mylesrankin/serverless-plugin-lex-bot 

Kind Regards,

Myles

**Comment by pavelsavara** [comment]
hi Myles, 

I do not expect to need any changes to this library myself any time soon as my project with it is over.
That said feel free to fork it or even contribute it to upstream. It's MIT licensed I think ;)
